# Generated by Django 4.1 on 2023-07-17 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('author', models.CharField(max_length=128, verbose_name='Author')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('song', models.FileField(upload_to='', verbose_name='Song file')),
                ('lyrics', models.TextField(verbose_name='Lyrics')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
            },
        ),
    ]
