# Generated by Django 4.1 on 2023-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='songs/%Y/%m/%d', verbose_name='Song file'),
        ),
    ]
